env:
    CODECOV_TOKEN: ENCRYPTED[b386dab525d9af8d807245b40c6812add427f42eb27fe8f3798bbf3970e338b45a93a2d208c08ae76abc2e9de7a31a32]

task:
  name: build-ipas+ios-test
  container:
    image: truongsinh/flutter-xcbuild:latest
  env:
    PATH: $PATH:/usr/local/bin
  activate_script: pub global activate flutter_plugin_tools
  matrix:
    - name: orignal
      script:
      - ./script/incremental_build.sh build-examples --ipa
      - ./script/incremental_build.sh ios-test  # @todo possible we don't have to build ipa anymore?
    - name: test only
      script:
      - ./script/incremental_build.sh ios-test  # @todo possible we don't have to build ipa anymore?
    - name: single flutter build
      script:
      - cd packages/device_info  # @todo possible we don't have to build ipa anymore?
      - flutter build ios
