env:
    CODECOV_TOKEN: ENCRYPTED[b386dab525d9af8d807245b40c6812add427f42eb27fe8f3798bbf3970e338b45a93a2d208c08ae76abc2e9de7a31a32]

task:
  name: build-ipas+ios-test
  container:
    image: truongsinh/flutter-xcbuild:latest
  env:
    PATH: $PATH:/usr/local/bin
  upgrade_script:
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
  build_script:
    - ./script/incremental_build.sh build-examples --ipa
    - ./script/incremental_build.sh ios-test  # @todo possible we don't have to build ipa anymore?
