env:
    CODECOV_TOKEN: ENCRYPTED[b386dab525d9af8d807245b40c6812add427f42eb27fe8f3798bbf3970e338b45a93a2d208c08ae76abc2e9de7a31a32]

task:
  name: build-ipas+ios-test
  container:
    image: mattpaletta/xcbuild:latest
  env:
    PATH: $PATH:/usr/local/bin
    matrix:
      PLUGIN_SHARDING: "--shardIndex 0 --shardCount 2"
      PLUGIN_SHARDING: "--shardIndex 1 --shardCount 2"
  setup_script:
    - git clone https://github.com/flutter/flutter.git
    - git fetch origin master
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
    - pub global activate flutter_plugin_tools
  build_script:
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - ./script/incremental_build.sh build-examples --ipa
    - ./script/incremental_build.sh ios-test  # @todo possible we don't have to build ipa anymore?
